#!/usr/bin/env node
// Interactive first-run wizard. Detects an existing acServer install on the
// host, suggests sensible defaults, and writes a minimal .env file the panel
// can start from. Run with:
//
//   npm run setup
//
// Safe to re-run: refuses to overwrite an existing .env unless --force is set.

'use strict';

const fs   = require('fs');
const os   = require('os');
const path = require('path');
const readline = require('readline');

const ROOT       = path.resolve(__dirname, '..');
const ENV_FILE   = path.join(ROOT, '.env');
const EXAMPLE    = path.join(ROOT, '.env.example');
const FORCE      = process.argv.includes('--force');

const CANDIDATE_ROOTS = [
  process.env.HOME && path.join(process.env.HOME, 'ac_server'),
  '/srv/assetto',
  '/opt/ac_server',
  '/srv/acserver',
].filter(Boolean);

function existsSync(p) { try { fs.accessSync(p); return true; } catch { return false; } }
function isDir(p)     { try { return fs.statSync(p).isDirectory(); } catch { return false; } }
function isFile(p)    { try { return fs.statSync(p).isFile();      } catch { return false; } }

function detectAcInstall() {
  for (const root of CANDIDATE_ROOTS) {
    if (!isDir(root)) continue;
    const layout = {
      root,
      cfg:     isDir(path.join(root, 'cfg'))     ? path.join(root, 'cfg')     : null,
      content: isDir(path.join(root, 'content')) ? path.join(root, 'content') : null,
      bin:     isFile(path.join(root, 'acServer')) ? path.join(root, 'acServer') : null,
    };
    if (layout.cfg && layout.content) return layout;
  }
  return null;
}

async function prompt(rl, question, fallback) {
  const suffix = fallback ? ` [${fallback}]` : '';
  return new Promise(resolve => {
    rl.question(`  ${question}${suffix}: `, (answer) => resolve((answer || '').trim() || fallback || ''));
  });
}

async function main() {
  console.log('');
  console.log('  ───────────────────────────────────────────');
  console.log('    Assetto Server Panel — first-run setup');
  console.log('  ───────────────────────────────────────────\n');

  if (existsSync(ENV_FILE) && !FORCE) {
    console.log(`  .env already exists at ${ENV_FILE}`);
    console.log('  Re-run with --force to overwrite it.\n');
    process.exit(0);
  }

  const detected = detectAcInstall();
  if (detected) {
    console.log(`  ✓ Auto-detected acServer install at: ${detected.root}\n`);
  } else {
    console.log('  No acServer install found in the conventional paths.');
    console.log('  You\'ll need to point each path at your actual install.\n');
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  const host = await prompt(rl, 'Bind to host (127.0.0.1 = local only; 0.0.0.0 = all interfaces)', '127.0.0.1');
  const port = await prompt(rl, 'Panel port', '3000');
  const acCfg     = await prompt(rl, 'AC_CFG_DIR (where server_cfg.ini lives)',     detected?.cfg     || '');
  const acContent = await prompt(rl, 'AC_CONTENT_DIR (cars/ + tracks/)',            detected?.content || '');
  const acBin     = await prompt(rl, 'AC_SERVER_BIN (the acServer executable)',    detected?.bin     || '');
  const acDir     = await prompt(rl, 'AC_SERVER_DIR (acServer working directory)', detected?.root    || (acBin ? path.dirname(acBin) : ''));

  const httpPort  = await prompt(rl, 'AC_HTTP_PORT (must match server_cfg.ini)', '8081');
  const useProxy  = (await prompt(rl, 'Behind a reverse proxy / Cloudflare Tunnel? (y/N)', 'n')).toLowerCase().startsWith('y');

  rl.close();

  const lines = [
    '# Generated by tools/setup.js. Edit freely; the wizard is just a one-shot helper.',
    '',
    `HOST=${host}`,
    `PORT=${port}`,
    '',
    `AC_CFG_DIR=${acCfg}`,
    `AC_CONTENT_DIR=${acContent}`,
    `AC_SERVER_BIN=${acBin}`,
    `AC_SERVER_DIR=${acDir}`,
    `AC_HTTP_PORT=${httpPort}`,
    '',
  ];
  if (useProxy) {
    lines.push('TRUST_PROXY=1');
    lines.push('# TRUST_PROXY_FROM=10.0.0.0/8,127.0.0.0/8   # override CF default if needed');
    lines.push('');
  }
  lines.push('# Optional knobs — see .env.example for the full list.');
  lines.push('# BACKUP_INTERVAL_HOURS=24');
  lines.push('# BACKUP_KEEP=14');
  lines.push('');

  fs.writeFileSync(ENV_FILE, lines.join('\n'), 'utf8');
  console.log('');
  console.log(`  ✓ Wrote ${ENV_FILE}`);
  console.log('');

  // Sanity-check the chosen paths and warn (but don't fail) on missing dirs.
  const checks = [
    ['AC_CFG_DIR',     acCfg,     'dir'],
    ['AC_CONTENT_DIR', acContent, 'dir'],
    ['AC_SERVER_BIN',  acBin,     'file'],
    ['AC_SERVER_DIR',  acDir,     'dir'],
  ];
  const bad = [];
  for (const [name, p, kind] of checks) {
    if (!p) { bad.push(`${name} is empty`); continue; }
    const ok = kind === 'dir' ? isDir(p) : isFile(p);
    if (!ok) bad.push(`${name} → ${p} does not exist or is the wrong type`);
  }
  if (bad.length) {
    console.log('  ⚠  Heads-up:');
    for (const b of bad) console.log(`     - ${b}`);
    console.log('     The panel will still start, but the affected features show errors until fixed.\n');
  }

  console.log('  Next: npm start   (or: docker compose up -d)');
  console.log('  Open: http://localhost:' + port);
  console.log('  Default credentials: Admin / Admin1234! (forced change on first login)\n');
}

main().catch(e => {
  console.error('setup failed:', e.message);
  process.exit(1);
});
